# -*- coding: utf-8 -*-
"""forwardcontracts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-z4iVbGEj11hSS8bnIRrW7lwGH0xCSI
"""

# Domestic Forward Contract P&L at Maturity Date
position = int(input("What is your asset position? 1 for long, 0 for short: "))
while (position != 1 or position != 0):
  position = int(input("Try again, 1 for long, 0 for short: "))
  if (position == 1 or position == 0):
    break

forward_price = float(input("Price of forward contract in USD: "))
spot_price = float(input("Spot price of asset in USD: "))
spot_minus_forward = abs(spot_price - forward_price)
forward_minus_spot = abs(-1 * (spot_price - forward_price))

if (position == 1):
    if (spot_price > forward_price) :
        print("You incurred a profit of $" + str(round(spot_minus_forward, 2)))
    elif (spot_price < forward_price) :
        print("You lost $" + str(round(forward_minus_spot, 2)))
    else :
        print("No profit or loss")
else :
    if (spot_price > forward_price) :
        print("You lost $" + str(round(spot_minus_forward, 2)))
    elif (spot_price < forward_price) :
        print("You incurred a profit of $" + str(round(forward_minus_spot, 2)))
    else :
        print("No profit or loss")
